name: Build and Publish P2P File Share

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ${{ matrix.os }}

        outputs:
            program_version: ${{ steps.get_program_version.outputs.VERSION }}

        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Extract program version
              id: get_program_version
              shell: bash
              run: |
                  # Extract the version from constants.py
                  V_LINE=$(grep "PROGRAM_VERSION =" src/constants.py | head -1)
                  VERSION=$(echo $V_LINE | cut -d'"' -f2)
                  echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.14"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Build with PyInstaller
              run: pyinstaller main.spec

            - name: Prepare artifact (Windows)
              if: runner.os == 'Windows'
              run: |
                  mkdir release
                  copy "dist\P2P-File-Share.exe" "release\P2P-File-Share-windows-x64.exe"

            - name: Prepare artifact (macOS)
              if: runner.os == 'macOS'
              run: |
                  mkdir release
                  cd dist
                  zip -r ../release/P2P-File-Share-macos-arm64.zip "P2P-File-Share.app"

            - name: Prepare artifact (Linux)
              if: runner.os == 'Linux'
              run: |
                  mkdir release
                  cp "dist/P2P-File-Share" "release/P2P-File-Share-linux-x64"

            - name: Upload build artifact
              uses: actions/upload-artifact@v6
              with:
                  name: build-${{ runner.os }}
                  path: release/

    publish:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v7
              with:
                  path: release

            - name: Create or update release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ needs.build.outputs.program_version }}
                  name: v${{ needs.build.outputs.program_version }}
                  body: "Release build"
                  files: release/**/*
                  make_latest: true
